name: build-publish-addon
on:
  push:
    branches:
      - build
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_NAME_PYTHON2: repository.sendtokodi
      REPO_URL_PYTHON2: "github.com/firsttris/repository.sendtokodi.git"
      REPO_NAME_PYTHON3: repository.sendtokodi.python3
      REPO_URL_PYTHON3: "github.com/firsttris/repository.sendtokodi.python3.git"
      ADDON_NAME: plugin.video.sendtokodi
      NAME: sendtokodi
      TOKEN: ${{secrets.PAT}}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Write new version to environment variable
        run: echo "VERSION=${{ steps.tag_version.outputs.new_version }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Build python3 addon
        run: $GITHUB_WORKSPACE/.github/scripts/build-addon.sh Matrix   
      - name: Create python3 zip
        uses: actions/upload-artifact@v2
        with:
          name: Addon-artifacts-python3
          path: |
             ${{ env.GITHUB_WORKSPACE }}/*
            !${{ env.GITHUB_WORKSPACE }}/.git*