name: build-publish-addon
on:
  push:
    branches:
      - clean_build
jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: clean_build
      - name: Write new version to environment variable
        run: echo "PLUGIN_VERSION=${{ steps.tag_version.outputs.new_version }}" >> $GITHUB_ENV
  build-leia:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build addon
        run: $GITHUB_WORKSPACE/.github/scripts/build-addon.sh Leia
      - name: Upload Addon-artifacts-Leia
        uses: actions/upload-artifact@v2
        with:
          name: Addon-artifacts-Leia
          path: "${{ runner.temp }}/Leia/*.zip"
  build-matrix:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build addon
        run: $GITHUB_WORKSPACE/.github/scripts/build-addon.sh Matrix     
      - name: Upload Addon-artifacts-Matrix
        uses: actions/upload-artifact@v2
        with:
          name: Addon-artifacts-Matrix
          path: "${{ runner.temp }}/Matrix/*.zip"
  publish-leia:
    needs: build-leia
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Addon-artifacts-Leia
      - name: Publish addon
        run: $GITHUB_WORKSPACE/.github/scripts/publish-addon.sh "github.com/firsttris/repository.sendtokodi.git" 
  publish-matrix:
    needs: build-leia
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Addon-artifacts-Matrix
      - name: Publish addon
        run: $GITHUB_WORKSPACE/.github/scripts/publish-addon.sh "github.com/firsttris/repository.sendtokodi.python3.git" 